// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"BabyDuck/token"
)

const (
	NoState    = -1
	NumStates  = 78
	NumSymbols = 112
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'p'
1: 'r'
2: 'o'
3: 'g'
4: 'r'
5: 'a'
6: 'm'
7: 'v'
8: 'a'
9: 'r'
10: 'm'
11: 'a'
12: 'i'
13: 'n'
14: 'e'
15: 'n'
16: 'd'
17: 'i'
18: 'f'
19: 'e'
20: 'l'
21: 's'
22: 'e'
23: 'w'
24: 'h'
25: 'i'
26: 'l'
27: 'e'
28: 'd'
29: 'o'
30: 'p'
31: 'r'
32: 'i'
33: 'n'
34: 't'
35: 'i'
36: 'n'
37: 't'
38: 'f'
39: 'l'
40: 'o'
41: 'a'
42: 't'
43: 'v'
44: 'o'
45: 'i'
46: 'd'
47: '.'
48: '"'
49: '"'
50: '+'
51: '-'
52: '*'
53: '/'
54: '>'
55: '<'
56: '!'
57: '='
58: '='
59: ';'
60: ':'
61: ','
62: '('
63: ')'
64: '{'
65: '}'
66: '['
67: ']'
68: 'e'
69: 'm'
70: 'p'
71: 't'
72: 'y'
73: ' '
74: '!'
75: '#'
76: '$'
77: '%'
78: '&'
79: '''
80: '('
81: ')'
82: '*'
83: '+'
84: ','
85: '-'
86: '.'
87: '/'
88: ':'
89: ';'
90: '<'
91: '='
92: '>'
93: '?'
94: '@'
95: '['
96: ']'
97: '^'
98: '_'
99: '`'
100: '{'
101: '|'
102: '}'
103: '~'
104: ' '
105: '\t'
106: '\n'
107: '\r'
108: 'a'-'z'
109: 'A'-'Z'
110: '0'-'9'
111: .
*/
