// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 40: // ['(','(']
			return 4
		case r == 41: // [')',')']
			return 5
		case r == 42: // ['*','*']
			return 6
		case r == 43: // ['+','+']
			return 7
		case r == 44: // [',',',']
			return 8
		case r == 45: // ['-','-']
			return 9
		case r == 47: // ['/','/']
			return 10
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 58: // [':',':']
			return 12
		case r == 59: // [';',';']
			return 13
		case r == 60: // ['<','<']
			return 14
		case r == 61: // ['=','=']
			return 15
		case r == 62: // ['>','>']
			return 16
		case r == 91: // ['[','[']
			return 17
		case r == 93: // [']',']']
			return 18
		case 97 <= r && r <= 99: // ['a','c']
			return 19
		case r == 100: // ['d','d']
			return 20
		case r == 101: // ['e','e']
			return 21
		case r == 102: // ['f','f']
			return 22
		case 103 <= r && r <= 104: // ['g','h']
			return 19
		case r == 105: // ['i','i']
			return 23
		case 106 <= r && r <= 108: // ['j','l']
			return 19
		case r == 109: // ['m','m']
			return 24
		case 110 <= r && r <= 111: // ['n','o']
			return 19
		case r == 112: // ['p','p']
			return 25
		case r == 113: // ['q','q']
			return 19
		case r == 114: // ['r','r']
			return 26
		case 115 <= r && r <= 117: // ['s','u']
			return 19
		case r == 118: // ['v','v']
			return 27
		case r == 119: // ['w','w']
			return 28
		case 120 <= r && r <= 122: // ['x','z']
			return 19
		case r == 123: // ['{','{']
			return 29
		case r == 125: // ['}','}']
			return 30
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 31
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 32
		case r == 33: // ['!','!']
			return 32
		case r == 34: // ['"','"']
			return 33
		case r == 35: // ['#','#']
			return 32
		case r == 36: // ['$','$']
			return 32
		case r == 37: // ['%','%']
			return 32
		case r == 38: // ['&','&']
			return 32
		case r == 39: // [''',''']
			return 34
		case r == 41: // [')',')']
			return 32
		case r == 42: // ['*','*']
			return 32
		case r == 43: // ['+','+']
			return 32
		case r == 44: // [',',',']
			return 32
		case r == 45: // ['-','-']
			return 32
		case r == 46: // ['.','.']
			return 32
		case r == 47: // ['/','/']
			return 32
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 58: // [':',':']
			return 32
		case r == 59: // [';',';']
			return 32
		case r == 60: // ['<','<']
			return 32
		case r == 61: // ['=','=']
			return 32
		case r == 62: // ['>','>']
			return 32
		case r == 63: // ['?','?']
			return 32
		case r == 64: // ['@','@']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 36
		case r == 91: // ['[','[']
			return 32
		case r == 93: // [']',']']
			return 32
		case r == 94: // ['^','^']
			return 32
		case r == 95: // ['_','_']
			return 32
		case r == 96: // ['`','`']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 37
		case r == 123: // ['{','{']
			return 32
		case r == 124: // ['|','|']
			return 32
		case r == 125: // ['}','}']
			return 32
		case r == 126: // ['~','~']
			return 32
		case r == 193: // [\u00c1,\u00c1]
			return 32
		case r == 201: // [\u00c9,\u00c9]
			return 32
		case r == 205: // [\u00cd,\u00cd]
			return 32
		case r == 209: // [\u00d1,\u00d1]
			return 32
		case r == 211: // [\u00d3,\u00d3]
			return 32
		case r == 216: // [\u00d8,\u00d8]
			return 32
		case r == 218: // [\u00da,\u00da]
			return 32
		case r == 220: // [\u00dc,\u00dc]
			return 32
		case r == 225: // [\u00e1,\u00e1]
			return 32
		case r == 233: // [\u00e9,\u00e9]
			return 32
		case r == 237: // [\u00ed,\u00ed]
			return 32
		case r == 241: // [\u00f1,\u00f1]
			return 32
		case r == 243: // [\u00f3,\u00f3]
			return 32
		case r == 248: // [\u00f8,\u00f8]
			return 32
		case r == 250: // [\u00fa,\u00fa]
			return 32
		case r == 252: // [\u00fc,\u00fc]
			return 32
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 47: // ['/','/']
			return 38
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 39
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 110: // ['a','n']
			return 19
		case r == 111: // ['o','o']
			return 42
		case 112 <= r && r <= 122: // ['p','z']
			return 19
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 107: // ['a','k']
			return 19
		case r == 108: // ['l','l']
			return 43
		case r == 109: // ['m','m']
			return 44
		case r == 110: // ['n','n']
			return 45
		case 111 <= r && r <= 122: // ['o','z']
			return 19
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 107: // ['a','k']
			return 19
		case r == 108: // ['l','l']
			return 46
		case 109 <= r && r <= 122: // ['m','z']
			return 19
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 101: // ['a','e']
			return 19
		case r == 102: // ['f','f']
			return 47
		case 103 <= r && r <= 109: // ['g','m']
			return 19
		case r == 110: // ['n','n']
			return 48
		case 111 <= r && r <= 122: // ['o','z']
			return 19
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case r == 97: // ['a','a']
			return 49
		case 98 <= r && r <= 122: // ['b','z']
			return 19
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 113: // ['a','q']
			return 19
		case r == 114: // ['r','r']
			return 50
		case 115 <= r && r <= 122: // ['s','z']
			return 19
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 100: // ['a','d']
			return 19
		case r == 101: // ['e','e']
			return 51
		case 102 <= r && r <= 122: // ['f','z']
			return 19
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case r == 97: // ['a','a']
			return 52
		case 98 <= r && r <= 110: // ['b','n']
			return 19
		case r == 111: // ['o','o']
			return 53
		case 112 <= r && r <= 122: // ['p','z']
			return 19
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 103: // ['a','g']
			return 19
		case r == 104: // ['h','h']
			return 54
		case 105 <= r && r <= 122: // ['i','z']
			return 19
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 32
		case r == 33: // ['!','!']
			return 32
		case r == 34: // ['"','"']
			return 33
		case r == 35: // ['#','#']
			return 32
		case r == 36: // ['$','$']
			return 32
		case r == 37: // ['%','%']
			return 32
		case r == 38: // ['&','&']
			return 32
		case r == 39: // [''',''']
			return 34
		case r == 41: // [')',')']
			return 32
		case r == 42: // ['*','*']
			return 32
		case r == 43: // ['+','+']
			return 32
		case r == 44: // [',',',']
			return 32
		case r == 45: // ['-','-']
			return 32
		case r == 46: // ['.','.']
			return 32
		case r == 47: // ['/','/']
			return 32
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 58: // [':',':']
			return 32
		case r == 59: // [';',';']
			return 32
		case r == 60: // ['<','<']
			return 32
		case r == 61: // ['=','=']
			return 32
		case r == 62: // ['>','>']
			return 32
		case r == 63: // ['?','?']
			return 32
		case r == 64: // ['@','@']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 36
		case r == 91: // ['[','[']
			return 32
		case r == 93: // [']',']']
			return 32
		case r == 94: // ['^','^']
			return 32
		case r == 95: // ['_','_']
			return 32
		case r == 96: // ['`','`']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 37
		case r == 123: // ['{','{']
			return 32
		case r == 124: // ['|','|']
			return 32
		case r == 125: // ['}','}']
			return 32
		case r == 126: // ['~','~']
			return 32
		case r == 193: // [\u00c1,\u00c1]
			return 32
		case r == 201: // [\u00c9,\u00c9]
			return 32
		case r == 205: // [\u00cd,\u00cd]
			return 32
		case r == 209: // [\u00d1,\u00d1]
			return 32
		case r == 211: // [\u00d3,\u00d3]
			return 32
		case r == 216: // [\u00d8,\u00d8]
			return 32
		case r == 218: // [\u00da,\u00da]
			return 32
		case r == 220: // [\u00dc,\u00dc]
			return 32
		case r == 225: // [\u00e1,\u00e1]
			return 32
		case r == 233: // [\u00e9,\u00e9]
			return 32
		case r == 237: // [\u00ed,\u00ed]
			return 32
		case r == 241: // [\u00f1,\u00f1]
			return 32
		case r == 243: // [\u00f3,\u00f3]
			return 32
		case r == 248: // [\u00f8,\u00f8]
			return 32
		case r == 250: // [\u00fa,\u00fa]
			return 32
		case r == 252: // [\u00fc,\u00fc]
			return 32
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 40: // ['(','(']
			return 32
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 32
		case r == 33: // ['!','!']
			return 32
		case r == 34: // ['"','"']
			return 33
		case r == 35: // ['#','#']
			return 32
		case r == 36: // ['$','$']
			return 32
		case r == 37: // ['%','%']
			return 32
		case r == 38: // ['&','&']
			return 32
		case r == 39: // [''',''']
			return 34
		case r == 41: // [')',')']
			return 32
		case r == 42: // ['*','*']
			return 32
		case r == 43: // ['+','+']
			return 32
		case r == 44: // [',',',']
			return 32
		case r == 45: // ['-','-']
			return 32
		case r == 46: // ['.','.']
			return 32
		case r == 47: // ['/','/']
			return 32
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 58: // [':',':']
			return 32
		case r == 59: // [';',';']
			return 32
		case r == 60: // ['<','<']
			return 32
		case r == 61: // ['=','=']
			return 32
		case r == 62: // ['>','>']
			return 32
		case r == 63: // ['?','?']
			return 32
		case r == 64: // ['@','@']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 36
		case r == 91: // ['[','[']
			return 32
		case r == 93: // [']',']']
			return 32
		case r == 94: // ['^','^']
			return 32
		case r == 95: // ['_','_']
			return 32
		case r == 96: // ['`','`']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 37
		case r == 123: // ['{','{']
			return 32
		case r == 124: // ['|','|']
			return 32
		case r == 125: // ['}','}']
			return 32
		case r == 126: // ['~','~']
			return 32
		case r == 193: // [\u00c1,\u00c1]
			return 32
		case r == 201: // [\u00c9,\u00c9]
			return 32
		case r == 205: // [\u00cd,\u00cd]
			return 32
		case r == 209: // [\u00d1,\u00d1]
			return 32
		case r == 211: // [\u00d3,\u00d3]
			return 32
		case r == 216: // [\u00d8,\u00d8]
			return 32
		case r == 218: // [\u00da,\u00da]
			return 32
		case r == 220: // [\u00dc,\u00dc]
			return 32
		case r == 225: // [\u00e1,\u00e1]
			return 32
		case r == 233: // [\u00e9,\u00e9]
			return 32
		case r == 237: // [\u00ed,\u00ed]
			return 32
		case r == 241: // [\u00f1,\u00f1]
			return 32
		case r == 243: // [\u00f3,\u00f3]
			return 32
		case r == 248: // [\u00f8,\u00f8]
			return 32
		case r == 250: // [\u00fa,\u00fa]
			return 32
		case r == 252: // [\u00fc,\u00fc]
			return 32
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 32
		case r == 33: // ['!','!']
			return 32
		case r == 34: // ['"','"']
			return 33
		case r == 35: // ['#','#']
			return 32
		case r == 36: // ['$','$']
			return 32
		case r == 37: // ['%','%']
			return 32
		case r == 38: // ['&','&']
			return 32
		case r == 39: // [''',''']
			return 34
		case r == 41: // [')',')']
			return 32
		case r == 42: // ['*','*']
			return 32
		case r == 43: // ['+','+']
			return 32
		case r == 44: // [',',',']
			return 32
		case r == 45: // ['-','-']
			return 32
		case r == 46: // ['.','.']
			return 32
		case r == 47: // ['/','/']
			return 32
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 58: // [':',':']
			return 32
		case r == 59: // [';',';']
			return 32
		case r == 60: // ['<','<']
			return 32
		case r == 61: // ['=','=']
			return 32
		case r == 62: // ['>','>']
			return 32
		case r == 63: // ['?','?']
			return 32
		case r == 64: // ['@','@']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 36
		case r == 91: // ['[','[']
			return 32
		case r == 93: // [']',']']
			return 32
		case r == 94: // ['^','^']
			return 32
		case r == 95: // ['_','_']
			return 32
		case r == 96: // ['`','`']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 37
		case r == 123: // ['{','{']
			return 32
		case r == 124: // ['|','|']
			return 32
		case r == 125: // ['}','}']
			return 32
		case r == 126: // ['~','~']
			return 32
		case r == 193: // [\u00c1,\u00c1]
			return 32
		case r == 201: // [\u00c9,\u00c9]
			return 32
		case r == 205: // [\u00cd,\u00cd]
			return 32
		case r == 209: // [\u00d1,\u00d1]
			return 32
		case r == 211: // [\u00d3,\u00d3]
			return 32
		case r == 216: // [\u00d8,\u00d8]
			return 32
		case r == 218: // [\u00da,\u00da]
			return 32
		case r == 220: // [\u00dc,\u00dc]
			return 32
		case r == 225: // [\u00e1,\u00e1]
			return 32
		case r == 233: // [\u00e9,\u00e9]
			return 32
		case r == 237: // [\u00ed,\u00ed]
			return 32
		case r == 241: // [\u00f1,\u00f1]
			return 32
		case r == 243: // [\u00f3,\u00f3]
			return 32
		case r == 248: // [\u00f8,\u00f8]
			return 32
		case r == 250: // [\u00fa,\u00fa]
			return 32
		case r == 252: // [\u00fc,\u00fc]
			return 32
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 32
		case r == 33: // ['!','!']
			return 32
		case r == 34: // ['"','"']
			return 33
		case r == 35: // ['#','#']
			return 32
		case r == 36: // ['$','$']
			return 32
		case r == 37: // ['%','%']
			return 32
		case r == 38: // ['&','&']
			return 32
		case r == 39: // [''',''']
			return 34
		case r == 41: // [')',')']
			return 32
		case r == 42: // ['*','*']
			return 32
		case r == 43: // ['+','+']
			return 32
		case r == 44: // [',',',']
			return 32
		case r == 45: // ['-','-']
			return 32
		case r == 46: // ['.','.']
			return 32
		case r == 47: // ['/','/']
			return 32
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 58: // [':',':']
			return 32
		case r == 59: // [';',';']
			return 32
		case r == 60: // ['<','<']
			return 32
		case r == 61: // ['=','=']
			return 32
		case r == 62: // ['>','>']
			return 32
		case r == 63: // ['?','?']
			return 32
		case r == 64: // ['@','@']
			return 32
		case 65 <= r && r <= 90: // ['A','Z']
			return 36
		case r == 91: // ['[','[']
			return 32
		case r == 93: // [']',']']
			return 32
		case r == 94: // ['^','^']
			return 32
		case r == 95: // ['_','_']
			return 32
		case r == 96: // ['`','`']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 37
		case r == 123: // ['{','{']
			return 32
		case r == 124: // ['|','|']
			return 32
		case r == 125: // ['}','}']
			return 32
		case r == 126: // ['~','~']
			return 32
		case r == 193: // [\u00c1,\u00c1]
			return 32
		case r == 201: // [\u00c9,\u00c9]
			return 32
		case r == 205: // [\u00cd,\u00cd]
			return 32
		case r == 209: // [\u00d1,\u00d1]
			return 32
		case r == 211: // [\u00d3,\u00d3]
			return 32
		case r == 216: // [\u00d8,\u00d8]
			return 32
		case r == 218: // [\u00da,\u00da]
			return 32
		case r == 220: // [\u00dc,\u00dc]
			return 32
		case r == 225: // [\u00e1,\u00e1]
			return 32
		case r == 233: // [\u00e9,\u00e9]
			return 32
		case r == 237: // [\u00ed,\u00ed]
			return 32
		case r == 241: // [\u00f1,\u00f1]
			return 32
		case r == 243: // [\u00f3,\u00f3]
			return 32
		case r == 248: // [\u00f8,\u00f8]
			return 32
		case r == 250: // [\u00fa,\u00fa]
			return 32
		case r == 252: // [\u00fc,\u00fc]
			return 32
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 55
		case r == 10: // ['\n','\n']
			return 55
		case r == 13: // ['\r','\r']
			return 55
		case r == 32: // [' ',' ']
			return 56
		case r == 33: // ['!','!']
			return 56
		case r == 35: // ['#','#']
			return 56
		case r == 36: // ['$','$']
			return 56
		case r == 37: // ['%','%']
			return 56
		case r == 38: // ['&','&']
			return 56
		case r == 39: // [''',''']
			return 57
		case r == 41: // [')',')']
			return 56
		case r == 42: // ['*','*']
			return 56
		case r == 43: // ['+','+']
			return 56
		case r == 44: // [',',',']
			return 56
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 56
		case r == 47: // ['/','/']
			return 56
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 58: // [':',':']
			return 56
		case r == 59: // [';',';']
			return 56
		case r == 60: // ['<','<']
			return 56
		case r == 61: // ['=','=']
			return 56
		case r == 62: // ['>','>']
			return 56
		case r == 63: // ['?','?']
			return 56
		case r == 64: // ['@','@']
			return 56
		case 65 <= r && r <= 90: // ['A','Z']
			return 59
		case r == 91: // ['[','[']
			return 56
		case r == 93: // [']',']']
			return 56
		case r == 94: // ['^','^']
			return 56
		case r == 95: // ['_','_']
			return 56
		case r == 96: // ['`','`']
			return 56
		case 97 <= r && r <= 122: // ['a','z']
			return 60
		case r == 123: // ['{','{']
			return 56
		case r == 124: // ['|','|']
			return 56
		case r == 125: // ['}','}']
			return 56
		case r == 126: // ['~','~']
			return 56
		case r == 193: // [\u00c1,\u00c1]
			return 56
		case r == 201: // [\u00c9,\u00c9]
			return 56
		case r == 205: // [\u00cd,\u00cd]
			return 56
		case r == 209: // [\u00d1,\u00d1]
			return 56
		case r == 211: // [\u00d3,\u00d3]
			return 56
		case r == 216: // [\u00d8,\u00d8]
			return 56
		case r == 218: // [\u00da,\u00da]
			return 56
		case r == 220: // [\u00dc,\u00dc]
			return 56
		case r == 225: // [\u00e1,\u00e1]
			return 56
		case r == 233: // [\u00e9,\u00e9]
			return 56
		case r == 237: // [\u00ed,\u00ed]
			return 56
		case r == 241: // [\u00f1,\u00f1]
			return 56
		case r == 243: // [\u00f3,\u00f3]
			return 56
		case r == 248: // [\u00f8,\u00f8]
			return 56
		case r == 250: // [\u00fa,\u00fa]
			return 56
		case r == 252: // [\u00fc,\u00fc]
			return 56
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 114: // ['a','r']
			return 19
		case r == 115: // ['s','s']
			return 62
		case 116 <= r && r <= 122: // ['t','z']
			return 19
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 111: // ['a','o']
			return 19
		case r == 112: // ['p','p']
			return 63
		case 113 <= r && r <= 122: // ['q','z']
			return 19
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 99: // ['a','c']
			return 19
		case r == 100: // ['d','d']
			return 64
		case 101 <= r && r <= 122: // ['e','z']
			return 19
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 110: // ['a','n']
			return 19
		case r == 111: // ['o','o']
			return 65
		case 112 <= r && r <= 122: // ['p','z']
			return 19
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 115: // ['a','s']
			return 19
		case r == 116: // ['t','t']
			return 66
		case 117 <= r && r <= 122: // ['u','z']
			return 19
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 104: // ['a','h']
			return 19
		case r == 105: // ['i','i']
			return 67
		case 106 <= r && r <= 122: // ['j','z']
			return 19
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 104: // ['a','h']
			return 19
		case r == 105: // ['i','i']
			return 68
		case 106 <= r && r <= 110: // ['j','n']
			return 19
		case r == 111: // ['o','o']
			return 69
		case 112 <= r && r <= 122: // ['p','z']
			return 19
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 115: // ['a','s']
			return 19
		case r == 116: // ['t','t']
			return 70
		case 117 <= r && r <= 122: // ['u','z']
			return 19
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 113: // ['a','q']
			return 19
		case r == 114: // ['r','r']
			return 71
		case 115 <= r && r <= 122: // ['s','z']
			return 19
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 104: // ['a','h']
			return 19
		case r == 105: // ['i','i']
			return 72
		case 106 <= r && r <= 122: // ['j','z']
			return 19
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 104: // ['a','h']
			return 19
		case r == 105: // ['i','i']
			return 73
		case 106 <= r && r <= 122: // ['j','z']
			return 19
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 55
		case r == 10: // ['\n','\n']
			return 55
		case r == 13: // ['\r','\r']
			return 55
		case r == 32: // [' ',' ']
			return 56
		case r == 33: // ['!','!']
			return 56
		case r == 35: // ['#','#']
			return 56
		case r == 36: // ['$','$']
			return 56
		case r == 37: // ['%','%']
			return 56
		case r == 38: // ['&','&']
			return 56
		case r == 39: // [''',''']
			return 57
		case r == 41: // [')',')']
			return 56
		case r == 42: // ['*','*']
			return 56
		case r == 43: // ['+','+']
			return 56
		case r == 44: // [',',',']
			return 56
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 56
		case r == 47: // ['/','/']
			return 56
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 58: // [':',':']
			return 56
		case r == 59: // [';',';']
			return 56
		case r == 60: // ['<','<']
			return 56
		case r == 61: // ['=','=']
			return 56
		case r == 62: // ['>','>']
			return 56
		case r == 63: // ['?','?']
			return 56
		case r == 64: // ['@','@']
			return 56
		case 65 <= r && r <= 90: // ['A','Z']
			return 59
		case r == 91: // ['[','[']
			return 56
		case r == 93: // [']',']']
			return 56
		case r == 94: // ['^','^']
			return 56
		case r == 95: // ['_','_']
			return 56
		case r == 96: // ['`','`']
			return 56
		case 97 <= r && r <= 122: // ['a','z']
			return 60
		case r == 123: // ['{','{']
			return 56
		case r == 124: // ['|','|']
			return 56
		case r == 125: // ['}','}']
			return 56
		case r == 126: // ['~','~']
			return 56
		case r == 193: // [\u00c1,\u00c1]
			return 56
		case r == 201: // [\u00c9,\u00c9]
			return 56
		case r == 205: // [\u00cd,\u00cd]
			return 56
		case r == 209: // [\u00d1,\u00d1]
			return 56
		case r == 211: // [\u00d3,\u00d3]
			return 56
		case r == 216: // [\u00d8,\u00d8]
			return 56
		case r == 218: // [\u00da,\u00da]
			return 56
		case r == 220: // [\u00dc,\u00dc]
			return 56
		case r == 225: // [\u00e1,\u00e1]
			return 56
		case r == 233: // [\u00e9,\u00e9]
			return 56
		case r == 237: // [\u00ed,\u00ed]
			return 56
		case r == 241: // [\u00f1,\u00f1]
			return 56
		case r == 243: // [\u00f3,\u00f3]
			return 56
		case r == 248: // [\u00f8,\u00f8]
			return 56
		case r == 250: // [\u00fa,\u00fa]
			return 56
		case r == 252: // [\u00fc,\u00fc]
			return 56
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case r == 40: // ['(','(']
			return 56
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 55
		case r == 10: // ['\n','\n']
			return 55
		case r == 13: // ['\r','\r']
			return 55
		case r == 32: // [' ',' ']
			return 56
		case r == 33: // ['!','!']
			return 56
		case r == 35: // ['#','#']
			return 56
		case r == 36: // ['$','$']
			return 56
		case r == 37: // ['%','%']
			return 56
		case r == 38: // ['&','&']
			return 56
		case r == 39: // [''',''']
			return 57
		case r == 41: // [')',')']
			return 56
		case r == 42: // ['*','*']
			return 56
		case r == 43: // ['+','+']
			return 56
		case r == 44: // [',',',']
			return 56
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 56
		case r == 47: // ['/','/']
			return 56
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 58: // [':',':']
			return 56
		case r == 59: // [';',';']
			return 56
		case r == 60: // ['<','<']
			return 56
		case r == 61: // ['=','=']
			return 56
		case r == 62: // ['>','>']
			return 56
		case r == 63: // ['?','?']
			return 56
		case r == 64: // ['@','@']
			return 56
		case 65 <= r && r <= 90: // ['A','Z']
			return 59
		case r == 91: // ['[','[']
			return 56
		case r == 93: // [']',']']
			return 56
		case r == 94: // ['^','^']
			return 56
		case r == 95: // ['_','_']
			return 56
		case r == 96: // ['`','`']
			return 56
		case 97 <= r && r <= 122: // ['a','z']
			return 60
		case r == 123: // ['{','{']
			return 56
		case r == 124: // ['|','|']
			return 56
		case r == 125: // ['}','}']
			return 56
		case r == 126: // ['~','~']
			return 56
		case r == 193: // [\u00c1,\u00c1]
			return 56
		case r == 201: // [\u00c9,\u00c9]
			return 56
		case r == 205: // [\u00cd,\u00cd]
			return 56
		case r == 209: // [\u00d1,\u00d1]
			return 56
		case r == 211: // [\u00d3,\u00d3]
			return 56
		case r == 216: // [\u00d8,\u00d8]
			return 56
		case r == 218: // [\u00da,\u00da]
			return 56
		case r == 220: // [\u00dc,\u00dc]
			return 56
		case r == 225: // [\u00e1,\u00e1]
			return 56
		case r == 233: // [\u00e9,\u00e9]
			return 56
		case r == 237: // [\u00ed,\u00ed]
			return 56
		case r == 241: // [\u00f1,\u00f1]
			return 56
		case r == 243: // [\u00f3,\u00f3]
			return 56
		case r == 248: // [\u00f8,\u00f8]
			return 56
		case r == 250: // [\u00fa,\u00fa]
			return 56
		case r == 252: // [\u00fc,\u00fc]
			return 56
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 55
		case r == 10: // ['\n','\n']
			return 55
		case r == 13: // ['\r','\r']
			return 55
		case r == 32: // [' ',' ']
			return 56
		case r == 33: // ['!','!']
			return 56
		case r == 35: // ['#','#']
			return 56
		case r == 36: // ['$','$']
			return 56
		case r == 37: // ['%','%']
			return 56
		case r == 38: // ['&','&']
			return 56
		case r == 39: // [''',''']
			return 57
		case r == 41: // [')',')']
			return 56
		case r == 42: // ['*','*']
			return 56
		case r == 43: // ['+','+']
			return 56
		case r == 44: // [',',',']
			return 56
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 56
		case r == 47: // ['/','/']
			return 56
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 58: // [':',':']
			return 56
		case r == 59: // [';',';']
			return 56
		case r == 60: // ['<','<']
			return 56
		case r == 61: // ['=','=']
			return 56
		case r == 62: // ['>','>']
			return 56
		case r == 63: // ['?','?']
			return 56
		case r == 64: // ['@','@']
			return 56
		case 65 <= r && r <= 90: // ['A','Z']
			return 59
		case r == 91: // ['[','[']
			return 56
		case r == 93: // [']',']']
			return 56
		case r == 94: // ['^','^']
			return 56
		case r == 95: // ['_','_']
			return 56
		case r == 96: // ['`','`']
			return 56
		case 97 <= r && r <= 122: // ['a','z']
			return 60
		case r == 123: // ['{','{']
			return 56
		case r == 124: // ['|','|']
			return 56
		case r == 125: // ['}','}']
			return 56
		case r == 126: // ['~','~']
			return 56
		case r == 193: // [\u00c1,\u00c1]
			return 56
		case r == 201: // [\u00c9,\u00c9]
			return 56
		case r == 205: // [\u00cd,\u00cd]
			return 56
		case r == 209: // [\u00d1,\u00d1]
			return 56
		case r == 211: // [\u00d3,\u00d3]
			return 56
		case r == 216: // [\u00d8,\u00d8]
			return 56
		case r == 218: // [\u00da,\u00da]
			return 56
		case r == 220: // [\u00dc,\u00dc]
			return 56
		case r == 225: // [\u00e1,\u00e1]
			return 56
		case r == 233: // [\u00e9,\u00e9]
			return 56
		case r == 237: // [\u00ed,\u00ed]
			return 56
		case r == 241: // [\u00f1,\u00f1]
			return 56
		case r == 243: // [\u00f3,\u00f3]
			return 56
		case r == 248: // [\u00f8,\u00f8]
			return 56
		case r == 250: // [\u00fa,\u00fa]
			return 56
		case r == 252: // [\u00fc,\u00fc]
			return 56
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 55
		case r == 10: // ['\n','\n']
			return 55
		case r == 13: // ['\r','\r']
			return 55
		case r == 32: // [' ',' ']
			return 56
		case r == 33: // ['!','!']
			return 56
		case r == 35: // ['#','#']
			return 56
		case r == 36: // ['$','$']
			return 56
		case r == 37: // ['%','%']
			return 56
		case r == 38: // ['&','&']
			return 56
		case r == 39: // [''',''']
			return 57
		case r == 41: // [')',')']
			return 56
		case r == 42: // ['*','*']
			return 56
		case r == 43: // ['+','+']
			return 56
		case r == 44: // [',',',']
			return 56
		case r == 45: // ['-','-']
			return 56
		case r == 46: // ['.','.']
			return 56
		case r == 47: // ['/','/']
			return 56
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case r == 58: // [':',':']
			return 56
		case r == 59: // [';',';']
			return 56
		case r == 60: // ['<','<']
			return 56
		case r == 61: // ['=','=']
			return 56
		case r == 62: // ['>','>']
			return 56
		case r == 63: // ['?','?']
			return 56
		case r == 64: // ['@','@']
			return 56
		case 65 <= r && r <= 90: // ['A','Z']
			return 59
		case r == 91: // ['[','[']
			return 56
		case r == 93: // [']',']']
			return 56
		case r == 94: // ['^','^']
			return 56
		case r == 95: // ['_','_']
			return 56
		case r == 96: // ['`','`']
			return 56
		case 97 <= r && r <= 122: // ['a','z']
			return 60
		case r == 123: // ['{','{']
			return 56
		case r == 124: // ['|','|']
			return 56
		case r == 125: // ['}','}']
			return 56
		case r == 126: // ['~','~']
			return 56
		case r == 193: // [\u00c1,\u00c1]
			return 56
		case r == 201: // [\u00c9,\u00c9]
			return 56
		case r == 205: // [\u00cd,\u00cd]
			return 56
		case r == 209: // [\u00d1,\u00d1]
			return 56
		case r == 211: // [\u00d3,\u00d3]
			return 56
		case r == 216: // [\u00d8,\u00d8]
			return 56
		case r == 218: // [\u00da,\u00da]
			return 56
		case r == 220: // [\u00dc,\u00dc]
			return 56
		case r == 225: // [\u00e1,\u00e1]
			return 56
		case r == 233: // [\u00e9,\u00e9]
			return 56
		case r == 237: // [\u00ed,\u00ed]
			return 56
		case r == 241: // [\u00f1,\u00f1]
			return 56
		case r == 243: // [\u00f3,\u00f3]
			return 56
		case r == 248: // [\u00f8,\u00f8]
			return 56
		case r == 250: // [\u00fa,\u00fa]
			return 56
		case r == 252: // [\u00fc,\u00fc]
			return 56
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 100: // ['a','d']
			return 19
		case r == 101: // ['e','e']
			return 74
		case 102 <= r && r <= 122: // ['f','z']
			return 19
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 115: // ['a','s']
			return 19
		case r == 116: // ['t','t']
			return 75
		case 117 <= r && r <= 122: // ['u','z']
			return 19
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case r == 97: // ['a','a']
			return 76
		case 98 <= r && r <= 122: // ['b','z']
			return 19
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 109: // ['a','m']
			return 19
		case r == 110: // ['n','n']
			return 77
		case 111 <= r && r <= 122: // ['o','z']
			return 19
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 109: // ['a','m']
			return 19
		case r == 110: // ['n','n']
			return 78
		case 111 <= r && r <= 122: // ['o','z']
			return 19
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 102: // ['a','f']
			return 19
		case r == 103: // ['g','g']
			return 79
		case 104 <= r && r <= 122: // ['h','z']
			return 19
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 116: // ['a','t']
			return 19
		case r == 117: // ['u','u']
			return 80
		case 118 <= r && r <= 122: // ['v','z']
			return 19
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 99: // ['a','c']
			return 19
		case r == 100: // ['d','d']
			return 81
		case 101 <= r && r <= 122: // ['e','z']
			return 19
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 107: // ['a','k']
			return 19
		case r == 108: // ['l','l']
			return 82
		case 109 <= r && r <= 122: // ['m','z']
			return 19
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 120: // ['a','x']
			return 19
		case r == 121: // ['y','y']
			return 83
		case r == 122: // ['z','z']
			return 19
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 115: // ['a','s']
			return 19
		case r == 116: // ['t','t']
			return 84
		case 117 <= r && r <= 122: // ['u','z']
			return 19
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 115: // ['a','s']
			return 19
		case r == 116: // ['t','t']
			return 85
		case 117 <= r && r <= 122: // ['u','z']
			return 19
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 113: // ['a','q']
			return 19
		case r == 114: // ['r','r']
			return 86
		case 115 <= r && r <= 122: // ['s','z']
			return 19
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 113: // ['a','q']
			return 19
		case r == 114: // ['r','r']
			return 87
		case 115 <= r && r <= 122: // ['s','z']
			return 19
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 100: // ['a','d']
			return 19
		case r == 101: // ['e','e']
			return 88
		case 102 <= r && r <= 122: // ['f','z']
			return 19
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case r == 97: // ['a','a']
			return 89
		case 98 <= r && r <= 122: // ['b','z']
			return 19
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 109: // ['a','m']
			return 19
		case r == 110: // ['n','n']
			return 90
		case 111 <= r && r <= 122: // ['o','z']
			return 19
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 108: // ['a','l']
			return 19
		case r == 109: // ['m','m']
			return 91
		case 110 <= r && r <= 122: // ['n','z']
			return 19
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 40
		case 65 <= r && r <= 90: // ['A','Z']
			return 41
		case 97 <= r && r <= 122: // ['a','z']
			return 19
		}
		return NoState
	},
}
