// Code generated by gocc; DO NOT EDIT.

package parser

import(
    "BabyDuck/ast"
    "BabyDuck/token"
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Program	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program : ProgramHeader FuncSection main Body end	<< func() (Attrib, error) {
            header := X[0].([]ast.Attrib)
            id := header[0].(string)
            vars := header[1].([]*ast.VarNode)
            body := X[3].([]ast.Attrib)

            // Inicializar programa como una función
            programNode, err := ast.DeclareFunction(id, vars, body)
            if err != nil {
                return nil, err
            }

            // Ejecutar programa
            return nil, ast.ExecuteFunction(programNode)
        }() >>`,
		Id:         "Program",
		NTType:     1,
		Index:      1,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (Attrib, error) {
            header := X[0].([]ast.Attrib)
            id := header[0].(string)
            vars := header[1].([]*ast.VarNode)
            body := X[3].([]ast.Attrib)

            // Inicializar programa como una función
            programNode, err := ast.DeclareFunction(id, vars, body)
            if err != nil {
                return nil, err
            }

            // Ejecutar programa
            return nil, ast.ExecuteFunction(programNode)
        }()
		},
	},
	ProdTabEntry{
		String: `ProgramHeader : program id semicolon VarSection	<< func() (Attrib, error) {
            id := string(X[1].(*token.Token).Lit)
            vars := X[3].([]*ast.VarNode)
            
            ast.InitProgram(id)
            if err := ast.ValidateVars(vars); err != nil {
                return nil, err
            }

            return []ast.Attrib{id, vars}, nil
        }() >>`,
		Id:         "ProgramHeader",
		NTType:     2,
		Index:      2,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (Attrib, error) {
            id := string(X[1].(*token.Token).Lit)
            vars := X[3].([]*ast.VarNode)
            
            ast.InitProgram(id)
            if err := ast.ValidateVars(vars); err != nil {
                return nil, err
            }

            return []ast.Attrib{id, vars}, nil
        }()
		},
	},
	ProdTabEntry{
		String: `VarSection : var VarList	<< X[1], nil >>`,
		Id:         "VarSection",
		NTType:     3,
		Index:      3,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `VarSection : "empty"	<< []*ast.VarNode{}, nil >>`,
		Id:         "VarSection",
		NTType:     3,
		Index:      4,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []*ast.VarNode{}, nil
		},
	},
	ProdTabEntry{
		String: `VarList : VarDeclaration VarList	<< append(X[0].([]*ast.VarNode), X[1].([]*ast.VarNode)...), nil >>`,
		Id:         "VarList",
		NTType:     4,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return append(X[0].([]*ast.VarNode), X[1].([]*ast.VarNode)...), nil
		},
	},
	ProdTabEntry{
		String: `VarList : VarDeclaration	<< X[0], nil >>`,
		Id:         "VarList",
		NTType:     4,
		Index:      6,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VarDeclaration : IdList colon Type semicolon	<< func() (Attrib, error) {
            ids := X[0].([]*token.Token)
            typ := string(X[2].(*token.Token).Lit)
            vars := []*ast.VarNode{}
            
            // Juntar ids en la lista de variables
            for _, id := range ids {
                vars = append(vars, &ast.VarNode{
                    Id: string(id.Lit),
                    Type: typ,
                    },
                )
            }

            return vars, nil
        }() >>`,
		Id:         "VarDeclaration",
		NTType:     5,
		Index:      7,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (Attrib, error) {
            ids := X[0].([]*token.Token)
            typ := string(X[2].(*token.Token).Lit)
            vars := []*ast.VarNode{}
            
            // Juntar ids en la lista de variables
            for _, id := range ids {
                vars = append(vars, &ast.VarNode{
                    Id: string(id.Lit),
                    Type: typ,
                    },
                )
            }

            return vars, nil
        }()
		},
	},
	ProdTabEntry{
		String: `IdList : id comma IdList	<< append([]*token.Token{X[0].(*token.Token)}, X[2].([]*token.Token)...), nil >>`,
		Id:         "IdList",
		NTType:     6,
		Index:      8,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return append([]*token.Token{X[0].(*token.Token)}, X[2].([]*token.Token)...), nil
		},
	},
	ProdTabEntry{
		String: `IdList : id	<< []*token.Token{X[0].(*token.Token)}, nil >>`,
		Id:         "IdList",
		NTType:     6,
		Index:      9,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []*token.Token{X[0].(*token.Token)}, nil
		},
	},
	ProdTabEntry{
		String: `Type : int	<< X[0], nil >>`,
		Id:         "Type",
		NTType:     7,
		Index:      10,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Type : float	<< X[0], nil >>`,
		Id:         "Type",
		NTType:     7,
		Index:      11,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncSection : FuncDeclaration FuncSection	<<  >>`,
		Id:         "FuncSection",
		NTType:     8,
		Index:      12,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncSection : "empty"	<<  >>`,
		Id:         "FuncSection",
		NTType:     8,
		Index:      13,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `FuncDeclaration : void id lparen FuncParams rparen lbracket VarSection Body rbracket semicolon	<< func() (Attrib, error) {
            id := string(X[1].(*token.Token).Lit)
            vars := append(X[3].([]*ast.VarNode), X[6].([]*ast.VarNode)...)
            body := X[7].([]ast.Attrib)

            // Crear y registrar la función
            return ast.DeclareFunction(id, vars, body)
        }() >>`,
		Id:         "FuncDeclaration",
		NTType:     9,
		Index:      14,
		NumSymbols: 10,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (Attrib, error) {
            id := string(X[1].(*token.Token).Lit)
            vars := append(X[3].([]*ast.VarNode), X[6].([]*ast.VarNode)...)
            body := X[7].([]ast.Attrib)

            // Crear y registrar la función
            return ast.DeclareFunction(id, vars, body)
        }()
		},
	},
	ProdTabEntry{
		String: `FuncParams : ParamList	<< X[0], nil >>`,
		Id:         "FuncParams",
		NTType:     10,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncParams : "empty"	<< []*ast.VarNode{}, nil >>`,
		Id:         "FuncParams",
		NTType:     10,
		Index:      16,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []*ast.VarNode{}, nil
		},
	},
	ProdTabEntry{
		String: `ParamList : Param comma ParamList	<< append([]*ast.VarNode{X[0].(*ast.VarNode)}, X[2].([]*ast.VarNode)...), nil >>`,
		Id:         "ParamList",
		NTType:     11,
		Index:      17,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return append([]*ast.VarNode{X[0].(*ast.VarNode)}, X[2].([]*ast.VarNode)...), nil
		},
	},
	ProdTabEntry{
		String: `ParamList : Param	<< []*ast.VarNode{X[0].(*ast.VarNode)}, nil >>`,
		Id:         "ParamList",
		NTType:     11,
		Index:      18,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []*ast.VarNode{X[0].(*ast.VarNode)}, nil
		},
	},
	ProdTabEntry{
		String: `Param : id colon Type	<< &ast.VarNode{
            Id: string(X[0].(*token.Token).Lit),
            Type: string(X[2].(*token.Token).Lit),
        }, nil >>`,
		Id:         "Param",
		NTType:     12,
		Index:      19,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.VarNode{
            Id: string(X[0].(*token.Token).Lit),
            Type: string(X[2].(*token.Token).Lit),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Body : lbrace StatementList rbrace	<< X[1], nil >>`,
		Id:         "Body",
		NTType:     13,
		Index:      20,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `StatementList : Statement StatementList	<< append([]ast.Attrib{X[0]}, X[1].([]ast.Attrib)...), nil >>`,
		Id:         "StatementList",
		NTType:     14,
		Index:      21,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return append([]ast.Attrib{X[0]}, X[1].([]ast.Attrib)...), nil
		},
	},
	ProdTabEntry{
		String: `StatementList : "empty"	<< []ast.Attrib{}, nil >>`,
		Id:         "StatementList",
		NTType:     14,
		Index:      22,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []ast.Attrib{}, nil
		},
	},
	ProdTabEntry{
		String: `Statement : Assign	<< X[0], nil >>`,
		Id:         "Statement",
		NTType:     15,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : Condition	<<  >>`,
		Id:         "Statement",
		NTType:     15,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : Cycle	<<  >>`,
		Id:         "Statement",
		NTType:     15,
		Index:      25,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : F_Call	<<  >>`,
		Id:         "Statement",
		NTType:     15,
		Index:      26,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : Print	<< X[0], nil >>`,
		Id:         "Statement",
		NTType:     15,
		Index:      27,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Assign : id assign Expression semicolon	<< &ast.AssignNode{
            Id: string(X[0].(*token.Token).Lit),
            Exp: X[2].(ast.Quad),
        }, nil >>`,
		Id:         "Assign",
		NTType:     16,
		Index:      28,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.AssignNode{
            Id: string(X[0].(*token.Token).Lit),
            Exp: X[2].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Expression : Exp	<< X[0], nil >>`,
		Id:         "Expression",
		NTType:     17,
		Index:      29,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Expression : Exp RelOp Exp	<< &ast.ExpressionNode{
            Left:  X[0].(ast.Quad),
            Op:    X[1].(string),
            Right: X[2].(ast.Quad),
        }, nil >>`,
		Id:         "Expression",
		NTType:     17,
		Index:      30,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.ExpressionNode{
            Left:  X[0].(ast.Quad),
            Op:    X[1].(string),
            Right: X[2].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `RelOp : gt	<< ">", nil >>`,
		Id:         "RelOp",
		NTType:     18,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ">", nil
		},
	},
	ProdTabEntry{
		String: `RelOp : lt	<< "<", nil >>`,
		Id:         "RelOp",
		NTType:     18,
		Index:      32,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return "<", nil
		},
	},
	ProdTabEntry{
		String: `RelOp : neq	<< "!=", nil >>`,
		Id:         "RelOp",
		NTType:     18,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return "!=", nil
		},
	},
	ProdTabEntry{
		String: `Exp : Exp plus Term	<< &ast.ExpressionNode{
            Op:    "+",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil >>`,
		Id:         "Exp",
		NTType:     19,
		Index:      34,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.ExpressionNode{
            Op:    "+",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Exp : Exp minus Term	<< &ast.ExpressionNode{
            Op:    "-",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil >>`,
		Id:         "Exp",
		NTType:     19,
		Index:      35,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.ExpressionNode{
            Op:    "-",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term	<< X[0], nil >>`,
		Id:         "Exp",
		NTType:     19,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Term times Factor	<< &ast.ExpressionNode{
            Op:    "*",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil >>`,
		Id:         "Term",
		NTType:     20,
		Index:      37,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.ExpressionNode{
            Op:    "*",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Term : Term divide Factor	<< &ast.ExpressionNode{
            Op:    "/",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil >>`,
		Id:         "Term",
		NTType:     20,
		Index:      38,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.ExpressionNode{
            Op:    "/",
            Left:  X[0].(ast.Quad),
            Right: X[2].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Term : Factor	<< X[0], nil >>`,
		Id:         "Term",
		NTType:     20,
		Index:      39,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : lparen Expression rparen	<< X[1], nil >>`,
		Id:         "Factor",
		NTType:     21,
		Index:      40,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `Factor : minus Atom	<< &ast.ExpressionNode{
            Op:    "-",
            Left:  &ast.VarNode{
                Type: "int",
                Value: "0",
            },
            Right: X[1].(ast.Quad),
        }, nil >>`,
		Id:         "Factor",
		NTType:     21,
		Index:      41,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.ExpressionNode{
            Op:    "-",
            Left:  &ast.VarNode{
                Type: "int",
                Value: "0",
            },
            Right: X[1].(ast.Quad),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Factor : Atom	<< X[0], nil >>`,
		Id:         "Factor",
		NTType:     21,
		Index:      42,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Atom : Cte	<< X[0], nil >>`,
		Id:         "Atom",
		NTType:     22,
		Index:      43,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Atom : id	<< &ast.VarNode{
            Id: string(X[0].(*token.Token).Lit),
        }, nil >>`,
		Id:         "Atom",
		NTType:     22,
		Index:      44,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.VarNode{
            Id: string(X[0].(*token.Token).Lit),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Cte : cte_int	<< &ast.VarNode{
            Type: "int",
            Value: string(X[0].(*token.Token).Lit),
        }, nil >>`,
		Id:         "Cte",
		NTType:     23,
		Index:      45,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.VarNode{
            Type: "int",
            Value: string(X[0].(*token.Token).Lit),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Cte : cte_float	<< &ast.VarNode{
            Type: "float",
            Value: string(X[0].(*token.Token).Lit),
        }, nil >>`,
		Id:         "Cte",
		NTType:     23,
		Index:      46,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.VarNode{
            Type: "float",
            Value: string(X[0].(*token.Token).Lit),
        }, nil
		},
	},
	ProdTabEntry{
		String: `Condition : if lparen Expression rparen Body ElseOptional semicolon	<<  >>`,
		Id:         "Condition",
		NTType:     24,
		Index:      47,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ElseOptional : else Body	<<  >>`,
		Id:         "ElseOptional",
		NTType:     25,
		Index:      48,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ElseOptional : "empty"	<<  >>`,
		Id:         "ElseOptional",
		NTType:     25,
		Index:      49,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Cycle : while lparen Expression rparen do Body semicolon	<<  >>`,
		Id:         "Cycle",
		NTType:     26,
		Index:      50,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_Call : id lparen F_Args rparen semicolon	<<  >>`,
		Id:         "F_Call",
		NTType:     27,
		Index:      51,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_Args : F_ArgsList	<<  >>`,
		Id:         "F_Args",
		NTType:     28,
		Index:      52,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_Args : "empty"	<<  >>`,
		Id:         "F_Args",
		NTType:     28,
		Index:      53,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `F_ArgsList : Expression comma F_ArgsList	<<  >>`,
		Id:         "F_ArgsList",
		NTType:     29,
		Index:      54,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F_ArgsList : Expression	<<  >>`,
		Id:         "F_ArgsList",
		NTType:     29,
		Index:      55,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Print : print lparen PrintVarList rparen semicolon	<< &ast.PrintNode{Items: X[2].([]ast.Attrib)}, nil >>`,
		Id:         "Print",
		NTType:     30,
		Index:      56,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return &ast.PrintNode{Items: X[2].([]ast.Attrib)}, nil
		},
	},
	ProdTabEntry{
		String: `PrintVarList : PrintVar	<< []ast.Attrib{X[0].(ast.Attrib)}, nil >>`,
		Id:         "PrintVarList",
		NTType:     31,
		Index:      57,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []ast.Attrib{X[0].(ast.Attrib)}, nil
		},
	},
	ProdTabEntry{
		String: `PrintVarList : PrintVar comma PrintVarList	<< append([]ast.Attrib{X[0].(ast.Attrib)}, X[2].([]ast.Attrib)...), nil >>`,
		Id:         "PrintVarList",
		NTType:     31,
		Index:      58,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return append([]ast.Attrib{X[0].(ast.Attrib)}, X[2].([]ast.Attrib)...), nil
		},
	},
	ProdTabEntry{
		String: `PrintVar : Expression	<< X[0], nil >>`,
		Id:         "PrintVar",
		NTType:     32,
		Index:      59,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `PrintVar : cte_string	<< string(X[0].(*token.Token).Lit), nil >>`,
		Id:         "PrintVar",
		NTType:     32,
		Index:      60,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return string(X[0].(*token.Token).Lit), nil
		},
	},
}
